final defaultConfigJSON={
  "name":{
    "maxLength":20,
    "minLength":8,
    "validatorRegex":[
      {
        "regex":"message"
      },
    ],
    "formatterRegex":"regex",
    "isMandatory":true,
  },
  "nickname":{
    "maxLength":20,
    "minLength":8,
    "validatorRegex":[
      {
        "regex":"message"
      },
    ],
    "formatterRegex":"regex",
    "isMandatory":true,
  },
  "email":{
    "maxLength":20,
    "minLength":8,
    "validatorRegex":[
      {
        "regex":"message"
      },
    ],
    "formatterRegex":"regex",
    "isMandatory":true,
  },
  "phone":{
    "maxLength":20,
    "minLength":8,
    "validatorRegex":[
      {
        "regex":"message"
      },
    ],
    "formatterRegex":"regex",
    "isMandatory":true,
  },
  "address":{
    "maxLength":20,
    "minLength":8,
    "validatorRegex":[
      {
        "regex":"message"
      },
    ],
    "formatterRegex":"regex",
    "isMandatory":false,
  },

};